<?php
/**
 * Plugin adapter for YaySMTP - WordPress Mail SMTP.
 * Generated by yaycommerce-init. Edit values as needed.
 */

defined( 'ABSPATH' ) || exit;

class YaysmtpPluginAdapter implements \YaySMTPScoped\YayCommerce\AdminShell\Contracts\PluginMenuAdapter {
    public function get_menu_title(): string         { return 'YaySMTP'; }
    public function get_page_title(): string         { return 'YaySMTP - WordPress Mail SMTP'; }
    public function get_menu_slug(): string          { return 'yaysmtp'; }
    public function get_settings_page_callback(): ?callable {
        return array( \YaySMTP\Page\Settings::getInstance(), 'settingsPage' );
    }
    public function get_settings_page_position(): ?int { return 180; }
    public function get_capability(): string         { return 'manage_options'; }
    public function get_plugin_basename(): string    { return YAY_SMTP_PLUGIN_BASENAME; }
    public function get_settings_label(): string     { return 'Settings'; }
    public function get_docs_url(): string           { return 'https://docs.yaycommerce.com/yaysmtp/'; }
    public function get_pro_url(): string            { return 'https://yaycommerce.com/yaysmtp-wordpress-mail-smtp/'; }
    public function wants_network_menu(): bool { return true; }
}
